/**
 * Centralized site configuration.
 * Allows env-based base URL for staging/preview environments.
 */
const DEFAULT_SITE_ORIGIN = 'https://www.cosmocrat.ai';

function normalizeOrigin(origin: string): string {
  return origin.endsWith('/') ? origin.slice(0, -1) : origin;
}

const origin = normalizeOrigin(process.env.NEXT_PUBLIC_SITE_URL || DEFAULT_SITE_ORIGIN);

export const siteConfig = {
  name: 'Cosmocrat',
  origin,
  url: origin,
  title: 'Cosmocrat | Enterprise AI Operating System & Control Plane',
  description:
    'Cosmocrat is the enterprise AI operating system that governs what AI is allowed to do, when it must stop, and who authorized it — turning AI execution into an auditable, accountable, and fail-closed asset.',
  // Versioned URL so social scrapers (X/Twitter, LinkedIn, Slack) fetch the current
  // card instead of a previously-cached one. The /og route is served immutable for a
  // year, so when the card CONTENT changes the URL must change to bust downstream
  // caches — bump ?v=N. Card generated by src/app/og/route.tsx; the /og.png rewrite
  // in next.config.js keeps old external references alive.
  ogImage: '/og?v=3',
  logo: 'https://storage.googleapis.com/cosmocrat/cosmocrat_logos_graphics/wordmark-logo_light.png',
  logoIcon: 'https://storage.googleapis.com/cosmocrat/cosmocrat_logos_graphics/sigil-gold.png',
  logoSchema: '/logo.png', // first-party PNG for schema compatibility
  sameAs: [
    'https://www.linkedin.com/company/cosmocrat/',
    'https://www.instagram.com/cosmocrat.ai/',
    'https://www.facebook.com/profile.php?id=61585886768903#',
  ],
  founder: {
    id: 'https://www.danmercede.com/#person',
    name: 'Dan Mercede',
    url: 'https://www.danmercede.com/',
    sameAs: [
      'https://www.linkedin.com/in/danmercede/',
      'https://x.com/danmercede',
    ],
  },
  parentOrganization: {
    id: 'https://www.orionapexcapital.com/#organization',
    name: 'Orion Apex Capital',
    url: 'https://www.orionapexcapital.com/',
    sameAs: ['https://www.linkedin.com/company/orionapexcapital'],
  },
} as const;

export type SiteConfig = typeof siteConfig;
